### ISSUE TITLE
Broken PBM saver on windows

### ISSUE THREAD

**Issue by plzombie** [ImageProcessing-ElectronicPublications/faxcoder#1]
@zvezdochiot  Я там добавил проектные файлы для вижуалстудии и удалил gnu-specific расширения, но не важно. Важно то, что `pbm.c` под виндой сохраняет файлы с какой-то полосой (сами файлы не битые, проверял на g4 в djvu)
Вот lzw:
![изображение](https://github.com/ImageProcessing-ElectronicPublications/faxcoder/assets/1690651/25d0eea8-68dd-49a0-9553-f27d6364384c)
Вот g4:
![изображение](https://github.com/ImageProcessing-ElectronicPublications/faxcoder/assets/1690651/343c93ed-7504-417b-b47f-7f4bfc1fe5aa)
Сегодня уже заниматься не буду. Но завтра постараюсь разобраться. Или тогда можно вообще выкинуть этот `pbm.c` и заменить на `stb_image.h` (я там как раз в своём форке добавил поддержку pbm) и мой `ppm_save.c`. Тебе решать.

**Comment by zvezdochiot** [comment]
@plzombie , сдвиг? А на сколько пикселей то? Щаз сам попробую потестить.

Потестил на случайном изображении 2056x500. Никаких сдигов. Попробую поменять размерность на бит.

Потестил на 2055x499, 2053x497 и 511x497. Ничего. Никаких сдвигов.

Провёл те же тесты на состояние current: https://github.com/ImageProcessing-ElectronicPublications/faxcoder/commit/14f5eae7af542a3dfee688388e9aea210149b976 . Ничего. Всё без сдвигов.

Протестил с MMR и DjVu. Декодировал DjVu `ddjvu`. Ничего. Никаких сдвигов. 

Воспроизвести твою картинку не могу. Магия?

PS: Сравнивал [GraphicsMagick](http://www.graphicsmagick.org/)-ом и [vbindiff](https://github.com/madsen/vbindiff)-ом.

PS2: Насчёт `stb`. Излишество. Нужды в нём нет, да и с tiff он работает хреново. Вот если бы `libtiff` прикрутить. 

PS3: Насчёт `pbm.c`. Можешь посмотреть [libpnmio](https://github.com/Special-graphic-formats/libpnmio).

**Comment by plzombie** [comment]
Не сдвиг, а вертикальная белая полоса. Причём, разная для g4 и lzw. Попробуй на моей аватарке попрактиковаться https://avatars.githubusercontent.com/u/1690651?v=4

Причём faxg4coder и faxlzwcoder дают немного разные полосы (я не знаю, почему). Если создать djvu, то там полосы нет, из чего я сделал вывод, что проблема, скорее всего, в сохранении pbm

Это именно в версии под винду, в любой сборке. Запусти свою под вайном

> PS2: Насчёт stb. Излишество. Нужды в нём нет, да и с tiff он работает хреново. Вот если бы libtiff прикрутить.

С tiff оригинал тоже не работает. А с pbm с недавних пор, как я запостил патч, стал работать stb

**Comment by zvezdochiot** [comment]
@plzombie say:
>Не сдвиг, а вертикальная белая полоса.

Да сдвиг, я тебе говорю. У тебя всё изображение уплыло вправо, а правая (как раз белая) часть соответственно заехала налево.

PS: И воспроизвести я это не смог никак.

**Comment by plzombie** [comment]
У меня под виндой работает на твоём mingw билде, на билде msvc14.2 под x86 и под x64. Без понятия абсолютно, почему

**Comment by zvezdochiot** [comment]
@plzombie , попробуй отключить:
https://github.com/ImageProcessing-ElectronicPublications/faxcoder/blob/14f5eae7af542a3dfee688388e9aea210149b976/win32/faxg4coder/faxg4coder.vcxproj#L47
Может компилятор лажает?

**Comment by plzombie** [comment]
Ты с флагом -p запускаешь? Попробуй без него. Без него у меня гарантированно получается хрень

**Comment by plzombie** [comment]
А значешь, в чём была проблема? Тот пресловутый "b" флаг и приобразование LF в CRLF

**Comment by plzombie** [comment]
Пофиксил в https://github.com/ImageProcessing-ElectronicPublications/faxcoder/commit/961b12732aaef50eb0fbe6bae11e8c8fb368c6a4

**Comment by zvezdochiot** [comment]
@plzombie , у меня тоже подозрение на `b` возникло, но ты в одном из коммитов вроде бы везде её добавил. Кто ж знал, что ещё 2 штуки остались? Ну да ладно.

**Comment by plzombie** [comment]
@zvezdochiot не делай пока релиз, я протестирую пайпы под виндой ещё

**Comment by zvezdochiot** [comment]
@plzombie , понял тебя. :+1:

**Comment by plzombie** [comment]
![изображение](https://github.com/ImageProcessing-ElectronicPublications/faxcoder/assets/1690651/833d2832-7bc6-410a-97a3-1e389a4d12f7)
![изображение](https://github.com/ImageProcessing-ElectronicPublications/faxcoder/assets/1690651/5646c8ff-431b-4bc7-9bca-c6fbc24b37d9)
@zvezdochiot  Сделал работающие пайпы. Всё перетестировал. Но ты на всякий случай тоже прогони тесты

**Comment by zvezdochiot** [comment]
@plzombie , слушай, а может `-g4` сделать дефолтом?

UPD: Не. Всё-таки логичнее `-g3`. Отбой.

PS: Всё норм по тестам. :+1:

**Comment by zvezdochiot** [comment]
@plzombie , :information_source: по поводу "бедноты" утилит в данном вопросике. Кое что есть в [mgetty-fax](http://mgetty.greenie.net/).

**Comment by plzombie** [comment]
@zvezdochiot А есть ли ещё какая-либо спека по формату (G4), кроме https://www.itu.int/rec/T-REC-T.6-198811-I/en ? А то тут в основном кодировщик описан

**Comment by zvezdochiot** [comment]
@plzombie , не, не знаю таких.
